### ISSUE TITLE
No module named "_libvips"

### ISSUE THREAD

**Issue by ReallyRad** [indus/kubi#14]
Hello,

After installing kubi with pip I'm unable to run any commands because of the following error : 

`ModuleNotFoundError: No module named '_libvips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Arthur\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Arthur\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Arthur\AppData\Local\Programs\Python\Python310\Scripts\kubi.exe\__main__.py", line 7, in <module>
  File "C:\Users\Arthur\AppData\Local\Programs\Python\Python310\lib\site-packages\kubi\kubi.py", line 347, in run
    main(sys.argv[1:])
  File "C:\Users\Arthur\AppData\Local\Programs\Python\Python310\lib\site-packages\kubi\kubi.py", line 343, in main
    kubi(args)
  File "C:\Users\Arthur\AppData\Local\Programs\Python\Python310\lib\site-packages\kubi\kubi.py", line 38, in kubi
    import pyvips
  File "C:\Users\Arthur\AppData\Local\Programs\Python\Python310\lib\site-packages\pyvips\__init__.py", line 70, in <module>
    gobject_lib = ffi.dlopen(_gobject_libname)
  File "C:\Users\Arthur\AppData\Local\Programs\Python\Python310\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Users\Arthur\AppData\Local\Programs\Python\Python310\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Users\Arthur\AppData\Local\Programs\Python\Python310\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'libgobject-2.0-0.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libgobject-2.0-0.dll'`

I'm using python 3.10

Any suggestions? 

thanks

**Comment by indus** [comment]
You have to also install the required libraries mentioned here: https://github.com/indus/kubi?tab=readme-ov-file#requirementsAm 09.02.2024 12:44 schrieb ReallyRad ***@***.***>:
Hello,
After installing kubi with pip I'm unable to run any commands because of the following error :
`ModuleNotFoundError: No module named '_libvips'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "C:\Users\Arthur\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
return run_code(code, main_globals, None,
File "C:\Users\Arthur\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in run_code
exec(code, run_globals)
File "C:\Users\Arthur\AppData\Local\Programs\Python\Python310\Scripts\kubi.exe_main.py", line 7, in 
File "C:\Users\Arthur\AppData\Local\Programs\Python\Python310\lib\site-packages\kubi\kubi.py", line 347, in run
main(sys.argv[1:])
File "C:\Users\Arthur\AppData\Local\Programs\Python\Python310\lib\site-packages\kubi\kubi.py", line 343, in main
kubi(args)
File "C:\Users\Arthur\AppData\Local\Programs\Python\Python310\lib\site-packages\kubi\kubi.py", line 38, in kubi
import pyvips
File "C:\Users\Arthur\AppData\Local\Programs\Python\Python310\lib\site-packages\pyvips_init.py", line 70, in 
gobject_lib = ffi.dlopen(_gobject_libname)
File "C:\Users\Arthur\AppData\Local\Programs\Python\Python310\lib\site-packages\cffi\api.py", line 150, in dlopen
lib, function_cache = _make_ffi_library(self, name, flags)
File "C:\Users\Arthur\AppData\Local\Programs\Python\Python310\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
backendlib = _load_backend_lib(backend, libname, flags)
File "C:\Users\Arthur\AppData\Local\Programs\Python\Python310\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
raise OSError(msg)
OSError: cannot load library 'libgobject-2.0-0.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libgobject-2.0-0.dll'`
I'm using python 3.10
Any suggestions?
thanks

**Comment by ReallyRad** [comment]
Hello,
numpy 1.26.4 and pyvips 2.2.2 are indeed installed. Could you share the recommended versions of python and of those two packages?
thanks

**Comment by indus** [comment]
I don't have the versions at hand (I can look for them later). Another problem may be a missing libvips binary in the path (you are working in Windows, right?). If that is the case you can set a flag in kubi that points to the libvips bin folder or add it to the path variable.Am 09.02.2024 15:12 schrieb ReallyRad ***@***.***>:
Hello,
numpy 1.26.4 and pyvips 2.2.2 are indeed installed. Could you share the recommended versions of python and of those two packages?
thanks

**Comment by indus** [comment]
@ReallyRad Did you had success already?

I would first try to follow the pyvips installation guide: https://github.com/libvips/pyvips?tab=readme-ov-file#windows-install
First download this: https://github.com/libvips/build-win64-mxe/releases/download/v8.14.4/vips-dev-w64-all-8.14.4.zip unzip it to your filesystem and then use kubi like so: `kubi --vips path/to/the/vips/bin ... ` (this will add the folder to path as described in the pyvips installation guide: https://github.com/indus/kubi/blob/main/src/kubi/kubi.py#L34-L36).

But because you aske - I'm running kubi with
python           3.10.2
pyvips            2.2.1
numpy           1.24.1
(Have not updated for a while ;-)

But atm I don't think the problem is caused by the versions.
